name: CI/CD Pipeline bot Discord Pace Papua
description: CICD pipeline for Discord Bot Pace Papua

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy-bot:
    name: Deploy Discord Bot to Production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            echo "✅ Memastikan direktori proyek tersedia"
            if [ ! -d "/home/gideonladiyo/PaceSorong_DiscordBot" ]; then
                echo "📁 Direktori belum ada, membuat direktori..."
                mkdir -p "/home/gideonladiyo/PaceSorong_DiscordBot"
            fi

            cd "$APP_DIR"

            if [ ! -d ".git" ]; then
                echo "🔄 Folder belum berisi repo Git, melakukan clone..."
                git clone https://github.com/gideonladiyo/PaceSorong_DiscordBot.git
            fi

            echo "📥 Menandai folder git sebagai aman"
            git config --global --add safe.directory "$APP_DIR"

            echo "📥 Pulling latest changes..."
            git pull origin main

            echo "🐳 Mengecek apakah container pace-discord-bot sedang berjalan"
            if [ "$(sudo docker ps -aq -f name=pace-discord-bot)" ]; then
                echo "🛑 Menghentikan dan menghapus container lama..."
                docker stop pace-discord-bot
                docker rm pace-discord-bot
            fi

            echo "🐳 Membuild dan menjalankan kontainer Docker"
            docker build -t pace-discord-bot .
            docker run -d \
              --name pace-discord-bot \
              --env-file .env \
              -v "$APP_DIR/data:/app/data" \
              pace-discord-bot

            echo "🚀 Bot berhasil dideploy