name: CI/CD Pipeline bot Discord Pace Papua
description: CICD pipeline for Discord Bot Pace Papua

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Pytest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run tests
        run: |
          export PYTHONPATH=.
          pytest

  deploy-bot:
    name: Deploy Discord Bot to Production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            echo "✅ Terhubung ke server"
            cd /home/PaceSorong_DiscordBot

            echo "📥 Menandai folder git sebagai aman"
            sudo git config --global --add safe.directory /home/PaceSorong_DiscordBot

            echo "📥 Pulling latest changes..."
            sudo git pull origin main

            echo "🐳 Membuild dan menjalankan kontainer Docker"
            sudo docker stop pace-discord-bot || true
            sudo docker rm pace-discord-bot || true
            sudo docker build -t pace-discord-bot .
            sudo docker run -d \
            --name pace-discord-bot \
            --env-file .env \
            -v /home/PaceSorong_DiscordBot/data:/app/data \
            pace-discord-bot

            echo "🚀 Bot berhasil dideploy"